version: "3.9"
services:

  actualite:
    build: .\ActualiteMicroService
    image: actualitems
    container_name: actualiteMS1
    ports:
      - "8085:8085"
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/ActualiteMS?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - eureka
      - mysql-db

  chambre:
    build: .\Chambre
    image: chambrems
    container_name: chambreMS1
    ports:
      - "8083:8083"
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/MicroChambre?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - eureka
      - mysql-db

  departement:
    build: .\DepartmentMS
    image: departmentms
    container_name: departmentMS1
    ports:
      - "8082:8082"
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/DepartmentMS?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - eureka
      - mysql-db

  univertsite:
    build: .\universiteback
    image: universitems
    container_name: universiteMS1
    ports:
      - "8089:8089"
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka
    depends_on:
      - "eureka"
  
  bloc:
    build: .\BlocMicroservice
    image: blocms
    container_name: blocMS1
    ports:
      - "8088:8088"
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka
    depends_on:
      - "eureka"

  foyer:
    build: .\UnivConnect
    image: univconnectms
    container_name: univconnectMS1
    ports:
      - "8084:8084"
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka
    depends_on:
      - "eureka"

  classe:
    build: .\Micro classe\ClassMicro
    image: classems
    container_name: classeMS1
    ports:
      - "8086:8086"
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/micro?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - eureka
      - mysql-db

  mysql-db:
    image: mysql:5.6
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_DATABASE=actualite
    ports:
      - "3306:3306"
    restart: unless-stopped

  eureka:
    build: .\EurekaDiscov
    image: eureka
    container_name: eurekaDiscovery
    ports:
      - "8761:8761"
    hostname: discovery
  
  gateway:
    build: .\Gateway
    image: gateway
    ports:
      - "8090:8090"
    environment:
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka
    depends_on:
      - eureka
      - actualite
      - chambre
      - departement
      - univertsite
      - bloc
      - foyer
      - classe